package br.allandemiranda.fx.robot.enums;

public enum DashboardStatus {
  CREATED,
  IMPORTING_MT5_DATA,
  IMPORTING_MT5_DATA_ERROR,
  MT5_DATA_REDY_TO_BUILD_ML,
  BUILDING_GARCH_SCENARIO,
  BUILDING_GARCH_SCENARIO_ERROR,
  GENERATING_ML_SCENARIOS,
  GENERATING_ML_SCENARIOS_ERROR,
  GENERATING_ML_MODEL,
  GENERATING_ML_MODEL_ERROR,
  REDY_TO_USE

}
