package br.allandemiranda.fx.robot.enums;

public enum DashboardStatus {
  //importing from MT5
  IMPORTING_SYMBOL,
  IMPORTING_SYMBOL_ERROR,
  IMPORTING_SYMBOL_COMPLETE,

  IMPORTING_TICKS,
  IMPORTING_TICKS_ERROR,
  IMPORTING_TICKS_COMPLETE,

  IMPORTING_CHART,
  IMPORTING_CHART_ERROR,
  IMPORTING_CHART_COMPLETE,

  IMPORTING_INPUT_OBJECTS,
  IMPORTING_INPUT_OBJECTS_ERROR,
  IMPORTING_INPUT_OBJECTS_COMPLETE,

  IMPORTING_CHART_OBJECTS,
  IMPORTING_CHART_OBJECTS_ERROR,
  IMPORTING_CHART_OBJECTS_COMPLETE,

  VALIDATING_SCOPE,
  VALIDATING_SCOPE_ERROR,
  VALIDATING_SCOPE_COMPLETE,

  IMPORTING_COMPLETED,

  // Async process generation Garch model
  GENERATING_GARCH_FORECASTS,
  GENERATING_GARCH_FORECASTS_ERROR,
  GENERATING_GARCH_FORECASTS_COMPLETE,

  BUILDING_GARCH_TRADINGS,
  BUILDING_GARCH_TRADINGS_ERROR,
  BUILDING_GARCH_TRADINGS_COMPLETE,

  GENERATING_GARCH_SCENARIO,
  GENERATING_GARCH_SCENARIO_ERROR,
  GENERATING_GARCH_SCENARIO_COMPLETE,

  GARCH_SCENARIOS_EXPORTING,
  GARCH_SCENARIOS_EXPORTING_ERROR,
  GARCH_SCENARIOS_EXPORTING_COMPLETE,

  // Generate the ML
  GENERATING_ML_MODEL,
  GENERATING_ML_MODEL_ERROR,
  GENERATING_ML_MODEL_COMPLETE,

  // Trading
  REDY_TO_USE
}
