package br.allandemiranda.fx.robot.enums;

public enum ExpertAdvisorStatus {
  CREATED,

  VALIDATING_SCOPE,
  VALIDATING_SCOPE_ERROR,
  VALIDATING_SCOPE_COMPLETE,

  BUILDING_START,
  BUILDING_ERROR,
  BUILDING_COMPLETE,

  GENERATING_ML_MODEL,
  GENERATING_ML_MODEL_ERROR,

  REDY_TO_USE
}
